### ISSUE TITLE
Triangulate modifier Blender 4.2.1

### ISSUE THREAD

**Issue by LexWermir** [Dangry98/modifier_list-for-Blender-4.0#3]
There is lack of "Keep normals" button in Triangulate modifier.

**Comment by Dangry98** [comment]
This is not a bug, it was removde in Blender 4.2 in the deafult modifier stack. It now alwayse preservs the normals automatically :)

**Comment by LexWermir** [comment]
Nope, this was a bug in 4.2.  In new 4.2.1 version the button is present. You can see it in stack mode, and it is not enabled automaticaly.

**Comment by Dangry98** [comment]
> Nope, this was a bug in 4.2. In new 4.2.1 version the button is present. You can see it in stack mode, and it is not enabled automaticaly.

Oh! Thank you so mutch for the reminder! I had completly forgoten about this, they [reverted ](https://projects.blender.org/blender/blender/pulls/125499) the change in 4.2.1 to the modifier after it turned out the submits that automaticley preservered the normals had some issues, I somehow thought they would make the change in Blender 4.3. 


I will make a update soon to fix it :)
