### ISSUE TITLE
Geometry node Modifer Buttons

### ISSUE THREAD

**Issue by AhmadHossam2002** [Dangry98/modifier_list-for-Blender-4.0#5]
the geometry node modifier don't show the "browse node to be linked" button or the "create new geometry node" button 
in both the list and stack mode
it will show u the "browse node to be linked" button if created a geometry node
im using blender Version 4.2.1
![Screenshot 2024-09-06 223527](https://github.com/user-attachments/assets/29e729ff-6aef-4b56-9e94-08a5ebe3b9ce)
![Screenshot 2024-09-06 223552](https://github.com/user-attachments/assets/ebfe4fd6-75bb-4c1e-85e6-7c55d984634b)
![Screenshot 2024-09-06 223826](https://github.com/user-attachments/assets/d8971ab9-f3c6-44d1-be3f-913713d6ce82)
also thanks guys for ur hardwork such great addon bye
out of topic if someone bothering that he cant search for node groups in the search bar u can alt A n get blender geometry node list with the search function assign s for it n its not a problem anymore so u can mention that to ppl if u want to

**Comment by Dangry98** [comment]
Hi, thanks for the report, but I am unable to replicate, works fine for me:
![image](https://github.com/user-attachments/assets/35fa10fe-59b6-4e76-8b8c-b7710303e9c2)
Since it also does not show up in the regular modifier UI, I would guess its most likely a Blender bug. Does it appear if Modifier List is disabeld? 

Please take a look in the consol  as well and see if there are any errors:
![image](https://github.com/user-attachments/assets/0fd68da9-8970-4751-bc3b-8e368365df6b)

**Comment by Dangry98** [comment]
Oh! Nvrm, it seems to happen if the modifier is added with the old leagacy meny
![image](https://github.com/user-attachments/assets/4e2ef645-aaca-409e-9dca-74f40e2838a8)

**Comment by Dangry98** [comment]
Fixed, please update modifier list, and thanks for the report!
